In [1]:
import pandas as pd
df = pd.read_csv('1August.csv')
df

,Gender,Age,GLUCOSE,HBA1C,CREATININE,BUN,HGB,Ferr,TROPONIN_I,CK,CK_MB,TRIGLYCERIDE,HDL_CHOLESTEROL,LDL_CHOLESTEROL,CRP,PCT,FT4,TSH,Disease
0,1,47,82.2,5.0,4.95,27.52,9.5,173.4,8292.1,62.9,7.1,98.8,48.3,101.9,23.8,0.24,0.81,3.840,0
1,1,64,30.0,5.1,1.57,39.00,12.2,140.7,2810.4,70.0,129.7,160.0,20.0,75.0,208.0,0.12,0.60,1.472,0
2,1,74,134.0,8.1,6.14,99.88,9.9,474.0,2722.0,230.0,22.2,141.0,28.0,67.0,12.4,0.20,1.20,1.944,0
3,1,58,209.7,8.1,7.07,66.31,11.1,158.0,15.0,61.9,16.4,79.4,27.3,65.9,64.8,0.21,1.07,2.644,0
4,1,46,98.0,5.2,3.67,20.62,11.7,354.0,28.2,127.6,13.2,149.0,40.0,117.0,17.0,0.32,1.00,1.332,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,1,65,93.0,4.9,0.64,12.70,13.7,179.9,14.3,92.9,7.3,90.0,48.7,102.3,2.9,0.29,0.60,1.001,8
2055,0,80,78.4,4.9,0.62,9.13,14.3,35.9,0.7,74.9,19.2,86.1,42.0,99.1,3.3,0.30,0.75,1.874,8
2056,1,74,80.0,4.9,0.80,18.79,14.1,86.9,8.7,48.0,17.4,103.0,43.9,97.4,2.1,0.21,1.24,2.513,8
2057,1,81,125.8,3.7,0.59,8.98,14.7,132.5,14.0,85.2,17.4,112.0,47.3,127.1,3.4,0.30,0.63,3.413,8
2058,0,75,118.0,5.1,0.91,16.17,14.3,163.6,7.4,88.0,8.6,129.0,55.2,97.4,4.6,0.19,0.58,2.636,8

In [2]:
from sklearn.tree import DecisionTreeClassifier

In [4]:
X = df.drop(columns=['Disease'])
y = df['Disease']

In [5]:
model = DecisionTreeClassifier()
model.fit(X, y)

DecisionTreeClassifier()

In [16]:
prediction = model.predict([[1, 65, 136, 6.9, 0.5, 12, 13.4, 116.4, 3.1, 62.9, 5.6, 98.0, 23.4, 103.5, 4.5, 0.34, 0.81, 1.201]])
prediction

array([2], dtype=int64)